// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2xKp1W5z8f_0_PIEgbYZTT7RIg5tjqSI',
    appId: '1:728856991324:web:249d8dcf7b9a7d3d5cb899',
    messagingSenderId: '728856991324',
    projectId: 'social-app-f4842',
    authDomain: 'social-app-f4842.firebaseapp.com',
    databaseURL: 'https://social-app-f4842-default-rtdb.firebaseio.com',
    storageBucket: 'social-app-f4842.appspot.com',
    measurementId: 'G-70K1JCW6EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMQhpd87JgZzpQKDW16OiTAio4y20kv6c',
    appId: '1:728856991324:android:2eb3c7bbbfd63a845cb899',
    messagingSenderId: '728856991324',
    projectId: 'social-app-f4842',
    databaseURL: 'https://social-app-f4842-default-rtdb.firebaseio.com',
    storageBucket: 'social-app-f4842.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDJBL8YESl46FEtEuhVrfCGhrkgSMdURY',
    appId: '1:728856991324:ios:0007dd1b70b01ae85cb899',
    messagingSenderId: '728856991324',
    projectId: 'social-app-f4842',
    databaseURL: 'https://social-app-f4842-default-rtdb.firebaseio.com',
    storageBucket: 'social-app-f4842.appspot.com',
    androidClientId: '728856991324-qe232rkg9jtvf6e4kvd69p2a847p2s5t.apps.googleusercontent.com',
    iosClientId: '728856991324-2lmm2b23hrvj0a33s6lc5vr89q7fq25u.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );
}
